### ISSUE TITLE
Add build caching for next.js apps

### ISSUE THREAD

**Issue by isBatak** [infinum/js-pipeline#11]
![image](https://user-images.githubusercontent.com/4128883/207383654-c9b48935-593f-4c06-ae77-77f6cb7aa814.png)

Explanation: https://nextjs.org/docs/messages/no-cache
Solution: https://nextjs.org/docs/advanced-features/ci-build-caching#github-actions

**Comment by DarkoKukovec** [comment]
Weird... I'll need to take a better look at this because we already have everything set up based on this documentation...
https://github.com/infinum/js-pipeline/blob/v1/.github/actions/bootstrap/action.yml#L52

**Comment by isBatak** [comment]
I'm afraid this is a real issue because this [action](https://github.com/infinum/JS-React-Example/actions/runs/3640550897/jobs/6145412359) is triggered for the change in the README file. 
Build should reuse .next cache in this case but it didn't.
![image](https://user-images.githubusercontent.com/4128883/207815297-8c3e3230-e945-4622-b1b8-890a7d636b67.png)
